# Generated by Django 5.1.5 on 2025-02-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RTO', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_video',
            name='RTO',
        ),
        migrations.DeleteModel(
            name='tbl_Article',
        ),
        migrations.DeleteModel(
            name='tbl_Video',
        ),
    ]
