# Generated by Django 5.1.5 on 2025-02-19 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0041_tbl_rto'),
        ('RTO', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Vehicledetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30)),
                ('vehicleuser_name', models.CharField(max_length=30)),
                ('vehicle_date', models.DateField(auto_now_add=True)),
                ('RTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_rto')),
            ],
        ),
    ]
