# Generated by Django 5.1.5 on 2025-02-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_video',
            name='MVD',
        ),
        migrations.DeleteModel(
            name='tbl_Article',
        ),
        migrations.DeleteModel(
            name='tbl_Video',
        ),
    ]
