# Generated by Django 5.1.5 on 2025-02-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0041_tbl_rto'),
        ('MVD', '0002_remove_tbl_video_mvd_delete_tbl_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_description', models.CharField(max_length=30)),
                ('request_file', models.FileField(upload_to='Assets/requestfile/photo/')),
                ('request_status', models.IntegerField(default=0)),
                ('MVD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mvd')),
                ('RTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_rto')),
            ],
        ),
    ]
