# Generated by Django 5.1.5 on 2025-03-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVD', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Request',
        ),
    ]
