# Generated by Django 5.1.5 on 2025-03-10 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0041_tbl_rto'),
        ('MVD', '0004_delete_tbl_request'),
        ('RTO', '0006_tbl_vehicledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_description', models.CharField(max_length=30)),
                ('request_status', models.IntegerField(default=0)),
                ('MVD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mvd')),
                ('RTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_rto')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTO.tbl_vehicledetails')),
            ],
        ),
    ]
