# Generated by Django 5.1.5 on 2025-01-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_tbl_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_district',
        ),
    ]
