# Generated by Django 5.1.5 on 2025-01-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_tbl_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
    ]
