# Generated by Django 5.1.5 on 2025-01-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_tbl_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=30)),
            ],
        ),
    ]
