# Generated by Django 5.1.5 on 2025-01-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0011_tbl_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_contact', models.CharField(max_length=30)),
                ('employee_email', models.CharField(max_length=30)),
                ('employee_address', models.CharField(max_length=30)),
                ('employee_salary', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_designation')),
            ],
        ),
    ]
