# Generated by Django 5.1.5 on 2025-02-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0012_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_subadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subadmin_name', models.CharField(max_length=30)),
                ('subadmin_email', models.CharField(max_length=30)),
                ('subadmin_password', models.CharField(max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_district')),
            ],
        ),
    ]
