# Generated by Django 5.1.5 on 2025-02-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0013_tbl_subadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
