# Generated by Django 5.1.5 on 2025-02-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0015_tbl_category_tbl_subcategory'),
        ('User', '0019_remove_tbl_feedback_user_delete_tbl_complaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
