# Generated by Django 5.1.5 on 2025-01-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0012_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=30)),
                ('user_photo', models.FileField(upload_to='Assets/User/photo/')),
                ('user_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
