# Generated by Django 5.1.5 on 2025-02-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_mvd'),
        ('User', '0007_delete_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Mvd',
        ),
    ]
