# Generated by Django 5.1.5 on 2025-02-10 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0013_tbl_subadmin'),
        ('Guest', '0005_delete_tbl_mvd'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Mvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvd_name', models.CharField(max_length=30)),
                ('mvd_email', models.CharField(max_length=30)),
                ('mvd_contact', models.CharField(max_length=30)),
                ('mvd_address', models.CharField(max_length=30)),
                ('mvd_photo', models.FileField(upload_to='Assets/Mvd/photo/')),
                ('mvd_proof', models.FileField(upload_to='Assets/Mvd/photo/')),
                ('mvd_password', models.CharField(max_length=30)),
                ('mvd_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
