# Generated by Django 5.1.5 on 2025-02-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_mvd'),
        ('User', '0011_remove_tbl_feedback_user_delete_tbl_complaint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_User',
        ),
    ]
