# Generated by Django 5.1.5 on 2025-02-12 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0015_tbl_category_tbl_subcategory'),
        ('Guest', '0013_remove_tbl_user_place_delete_tbl_mvd_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Mvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvd_name', models.CharField(max_length=30)),
                ('mvd_email', models.CharField(max_length=30)),
                ('mvd_contact', models.CharField(max_length=30)),
                ('mvd_address', models.CharField(max_length=30)),
                ('mvd_photo', models.FileField(upload_to='Assets/Mvd/photo/')),
                ('mvd_proof', models.FileField(upload_to='Assets/Mvd/photo/')),
                ('mvd_password', models.CharField(max_length=30)),
                ('mvd_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=30)),
                ('user_photo', models.FileField(upload_to='Assets/User/photo/')),
                ('user_proof', models.FileField(upload_to='Assets/User/photo/')),
                ('user_password', models.CharField(max_length=30)),
                ('user_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
