# Generated by Django 5.1.5 on 2025-02-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_initial'),
        ('User', '0021_delete_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Mvd',
        ),
    ]
