# Generated by Django 5.1.5 on 2025-02-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0021_tbl_rto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_RTO',
        ),
    ]
