# Generated by Django 5.1.5 on 2025-02-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0017_tbl_category_tbl_subcategory'),
        ('Guest', '0026_delete_tbl_rto'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_RTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rto_name', models.CharField(max_length=30)),
                ('rto_email', models.CharField(max_length=30)),
                ('rto_contact', models.CharField(max_length=30)),
                ('rto_address', models.CharField(max_length=30)),
                ('rto_photo', models.FileField(upload_to='Assets/RTO/photo/')),
                ('rto_proof', models.FileField(upload_to='Assets/RTO/photo/')),
                ('rto_password', models.CharField(max_length=30)),
                ('rto_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
