# Generated by Django 5.1.5 on 2025-02-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0035_tbl_rto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Rto',
        ),
    ]
