# Generated by Django 5.1.5 on 2025-02-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0037_tbl_rto_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_RTO_Model',
        ),
    ]
