# Generated by Django 5.1.5 on 2025-02-03 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_subject', models.CharField(max_length=30)),
                ('com_complaint', models.CharField(max_length=30)),
                ('com_date', models.DateField(auto_now_add=True)),
                ('com_status', models.IntegerField(default=0)),
                ('reply_complaint', models.CharField(max_length=30)),
                ('reply_date', models.DateField(null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
