# Generated by Django 5.1.5 on 2025-02-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Feedback',
        ),
    ]
