# Generated by Django 5.1.5 on 2025-02-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Complaint',
        ),
    ]
