# Generated by Django 5.1.5 on 2025-02-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Complaint',
        ),
    ]
