# Generated by Django 5.1.5 on 2025-02-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='User',
        ),
        migrations.DeleteModel(
            name='tbl_Complaint',
        ),
        migrations.DeleteModel(
            name='tbl_Feedback',
        ),
    ]
