# Generated by Django 5.1.5 on 2025-02-12 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0015_tbl_category_tbl_subcategory'),
        ('Guest', '0014_initial'),
        ('User', '0017_remove_tbl_feedback_user_delete_tbl_complaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=30)),
                ('complaint_description', models.CharField(max_length=30)),
                ('complaint_photo', models.FileField(upload_to='Assets/Complaint/photo/')),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('reply_complaint', models.CharField(max_length=30)),
                ('complaint_amount', models.CharField(max_length=30)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_category')),
                ('MVD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mvd')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=30)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
