# Generated by Django 5.1.5 on 2025-02-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Complaint',
        ),
    ]
