# Generated by Django 5.1.5 on 2025-03-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Complaint',
        ),
    ]
