# Generated by Django 5.1.5 on 2025-03-04 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0017_tbl_category_tbl_subcategory'),
        ('Guest', '0041_tbl_rto'),
        ('RTO', '0006_tbl_vehicledetails'),
        ('User', '0025_delete_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_description', models.CharField(max_length=30)),
                ('complaint_photo', models.FileField(upload_to='Assets/Complaint/photo/')),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('reply_complaint', models.CharField(max_length=30)),
                ('complaint_amount', models.CharField(max_length=30)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_category')),
                ('MVD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mvd')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('vehicle_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTO.tbl_vehicledetails')),
            ],
        ),
    ]
