# Generated by Django 5.2 on 2025-04-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_tbl_complaint_complaint_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_multipleviolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_complaint')),
            ],
        ),
    ]
