# Generated by Django 5.2 on 2025-04-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_tbl_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_points',
            name='point_credited',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_points',
            name='point_widthdrawed',
            field=models.IntegerField(null=True),
        ),
    ]
