# Generated by Django 5.2 on 2025-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_alter_tbl_points_point_widthdrawed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_points',
            name='point_credited',
            field=models.IntegerField(default=0),
        ),
    ]
