# Generated by Django 5.2 on 2025-04-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_alter_tbl_points_point_credited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_points',
        ),
    ]
