# Generated by Django 5.2 on 2025-04-28 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0041_tbl_rto'),
        ('User', '0034_delete_tbl_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_credited', models.IntegerField(default=0)),
                ('point_widthdrawed', models.IntegerField(default=0)),
                ('point_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
